feat(ext): Unsafe sqlite
tryandromeda/andromeda pull request #15
Opened 2024-08-02 05:41 UTC by load1n9

2024-08-02 06:37 UTC, marc2332 requested changes

2024-08-02 06:37 UTC, marc2332 commented on cli/Cargo.toml
> +[dev-dependencies]
nit: debris?

2024-08-02 06:37 UTC, marc2332 commented on cli/Cargo.toml
> +default = []
question: any reason to put this here already?

2024-08-02 06:37 UTC, marc2332 commented on core/src/ext/sqlite.rs
> +        });
Doesn't seem like a good idea to open a new sqlite connection at startup, it should be manually triggered by the user by calling an op, just like `internal_sqlite_execute`

2024-08-02 06:37 UTC, marc2332 commented on runtime/global.d.ts
Is `Storage` supposed to be backed by the sqlite? It seems to be missing an actual implementation right?

2024-08-02 06:37 UTC, marc2332 commented on core/src/ext/sqlite.rs
> +        });
I now see it might be used for backing a localStorage-like API, in that case, how big does embedding sqlite make the binary, and I also wonder what's the performance hit for startup. Perhaps we could lazy load the connection whenever `internal_sqlite_execute` is executed, I think that would be the best thing to avoid a performance hit (if there is any).

2024-08-02 06:37 UTC, marc2332 commented on core/src/ext/mod.rs
> +#[cfg(feature = "unsafe-sqlite")]
question: Why is it called `unsafe-sqlite` instead of just `sqlite`? Just curious

2024-08-02 16:20 UTC, load1n9 commented on core/src/ext/sqlite.rs
> +        });
i might do that when we can pass through pointers or external objects

2024-08-02 16:21 UTC, load1n9 commented on core/src/ext/mod.rs
> +#[cfg(feature = "unsafe-sqlite")]
because its super unsafe atm and should only be used when testing new features that may depend on sqlite

2024-08-02 19:14 UTC, marc2332 commented on core/src/ext/sqlite.rs
> +        });
You mean resources? We can already do that

2024-08-04 07:50 UTC, marc2332 commented
You got a few conflicts @load1n9

2024-08-04 20:23 UTC, load1n9 commented
> You got a few conflicts @load1n9

yeah lets not use this pr, we can use it as reference for anything needing sqlite

2025-06-08 06:12 UTC, closed without merging