feat: get cli args
tryandromeda/andromeda pull request #25
Opened 2024-08-08 19:49 UTC by load1n9

2024-08-08 20:40 UTC, lino-levan commented on runtime/src/ext/process.rs
> +        // TODO: This should be an array
What, please elaborate

2024-08-08 22:00 UTC, marc2332 requested changes

2024-08-08 22:00 UTC, marc2332 commented on runtime/src/ext/process.rs
> +/// Process extension for Nova
Nova ? :trollface: 
```suggestion
/// Process extension for Nova
```

2024-08-08 22:00 UTC, marc2332 commented on runtime/src/ext/process.rs
> +        // TODO: This should be an array
+1

2024-08-09 02:00 UTC, load1n9 commented on runtime/src/ext/process.rs
> +        // TODO: This should be an array
oh sorry left that there

2024-08-09 05:39 UTC, lino-levan approved these changes
Don't love that we're basing our nova off of a branch but /shrug

2024-08-09 05:42 UTC, merged